// ---------------------------------------------------------------------------
// Tariffs — update these constants when pricing changes
//
// The canonical table lives in `shared/pricing.json` (the code home of
// docs/viral-flow.md §10). These numbers are duplicated here — and in
// `src/credits.ts` — rather than imported, because the Cloud Functions
// `node16` build, the Vite client build, and the Firebase deploy boundary
// (only `functions/` is uploaded) make a single runtime-shared module awkward.
// `ct/pricing-parity.ct.ts` fails when any copy drifts from the JSON, so the
// duplication is guarded, never silent. Update all three together.
// ---------------------------------------------------------------------------

/** Price per 1 M input tokens — Gemini 2.5 Pro (prompts ≤ 200 k tokens). */
export const GEMINI_PRO_INPUT_PRICE_PER_M = 1.25; // USD

/** Price per 1 M output tokens — Gemini 2.5 Pro (incl. thinking, prompts ≤ 200 k). */
export const GEMINI_PRO_OUTPUT_PRICE_PER_M = 10.0; // USD

/** Price per image generated by Gemini 2.5 Flash Image. */
export const IMAGE_GENERATION_PRICE_USD = 0.039; // USD

// ---------------------------------------------------------------------------
// Credit economics
// ---------------------------------------------------------------------------

/** 1 user-facing credit = this many USD. */
export const CREDIT_VALUE_USD = 0.01;

/** Fraction of credit value available for AI spending (80 % after 20 % platform fee). */
export const AI_BUDGET_RATIO = 0.8;

/** 1 credit = this many USD of AI budget. */
export const CREDIT_AI_USD = CREDIT_VALUE_USD * AI_BUDGET_RATIO; // 0.008

/** Minimum top-up amount in credits (floor set by Stripe transaction costs). */
export const MIN_TOPUP_CREDITS = 75;

/** Per-action credit prices charged for each renovation edit. */
export const ACTION_CREDITS = {
  remove: 5,
  colorChange: 10,
  freePrompt: 10,
  applyMaterial: 10,
  addFurniture: 10,
} as const;

/** The actions a user can pick on the choose-action step. */
export type RenovationAction = keyof typeof ACTION_CREDITS;

// ---------------------------------------------------------------------------
// Conversion helpers
// ---------------------------------------------------------------------------

/** Convert a USD AI cost to credits (rounded up to nearest whole credit). */
export function usdToCredits(usd: number): number {
  return Math.ceil(usd / CREDIT_AI_USD);
}

/** Convert credits to the USD AI budget they represent. */
export function creditsToUsd(credits: number): number {
  return credits * CREDIT_AI_USD;
}

// ---------------------------------------------------------------------------
// Chat cost calculation (Gemini 2.5 Pro)
// ---------------------------------------------------------------------------

/**
 * Exact USD cost for a chat turn.
 * `outputTokens` should include both candidate and thinking tokens —
 * the Gemini pricing bills them at the same output rate.
 */
export function chatCostUsd(inputTokens: number, outputTokens: number): number {
  return (
    (inputTokens / 1_000_000) * GEMINI_PRO_INPUT_PRICE_PER_M +
    (outputTokens / 1_000_000) * GEMINI_PRO_OUTPUT_PRICE_PER_M
  );
}

/** Exact credit cost for a chat turn (rounded up). */
export function chatCostCredits(
  inputTokens: number,
  outputTokens: number,
): number {
  return usdToCredits(chatCostUsd(inputTokens, outputTokens));
}

/**
 * Worst-case credit estimate before generating.
 * Uses `maxOutputTokens` as the upper bound for output.
 */
export function estimateChatCredits(
  inputTokens: number,
  maxOutputTokens: number,
): number {
  return chatCostCredits(inputTokens, maxOutputTokens);
}

/**
 * Maximum total output tokens (response + thinking) affordable given
 * a credit budget and a known input token count.
 * Returns 0 when the input alone exceeds the budget.
 */
export function maxOutputTokensForBudget(
  budgetCredits: number,
  inputTokens: number,
): number {
  const budgetUsd = creditsToUsd(budgetCredits);
  const inputCostUsd = (inputTokens / 1_000_000) * GEMINI_PRO_INPUT_PRICE_PER_M;
  const remainingUsd = budgetUsd - inputCostUsd;
  if (remainingUsd <= 0) return 0;
  return Math.floor((remainingUsd / GEMINI_PRO_OUTPUT_PRICE_PER_M) * 1_000_000);
}

// ---------------------------------------------------------------------------
// Image generation cost
// ---------------------------------------------------------------------------

/** Credits for one image generation (rounded up). */
export function imageGenerationCredits(): number {
  return usdToCredits(IMAGE_GENERATION_PRICE_USD);
}
