project_id         = "prepaid-ai-dev"
environment        = "dev"
region             = "europe-west1"
firestore_location = "eur3"
public_url         = "https://prepaid-ai-dev.web.app"
ai_backend         = "vertex"
