project_id         = "payasyougo-production"
environment        = "production"
region             = "europe-west4"
firestore_location = "europe-west4"
public_url         = "https://payasyougo.app"
ai_backend         = "vertex"
ai_region          = "global"
stripe_backend     = "stripe"
