project_id         = "payasyougo-production"
environment        = "production"
region             = "europe-west1"
firestore_location = "eur3"
public_url         = "https://payasyougo.app"
ai_backend         = "vertex"
stripe_backend     = "stripe"
