/**
 * Client-side copy of the pricing constants.
 *
 * The canonical table lives in `shared/pricing.json` (the code home of
 * docs/viral-flow.md §10). It is duplicated here — and in
 * `functions/src/credits.ts` — rather than imported, because the Vite client
 * build, the Cloud Functions `node16` build, and the Firebase deploy boundary
 * (only `functions/` is uploaded) make a single runtime-shared module awkward.
 * `ct/pricing-parity.ct.ts` fails when any copy drifts from `shared/pricing.json`,
 * so the duplication is guarded, never silent. Update all three together.
 */

/** Price per 1 M Gemini 2.5 Pro input tokens (USD). */
export const GEMINI_PRO_INPUT_PRICE_PER_M = 1.25;

/** Price per image generated by Gemini 2.5 Flash Image (USD). */
export const IMAGE_GENERATION_PRICE_USD = 0.039;

/** 1 user-facing credit, in USD. */
export const CREDIT_VALUE_USD = 0.01;

/** Fraction of credit value available for AI spending (80% after 20% platform fee). */
export const AI_BUDGET_RATIO = 0.8;

/** USD of AI budget unlocked per credit. */
export const CREDIT_AI_USD = CREDIT_VALUE_USD * AI_BUDGET_RATIO; // 0.008

/** Convert credits to USD price for the user. */
export function creditsToUsd(credits: number): number {
  return credits * CREDIT_VALUE_USD;
}

/** Credits required for a single image generation (rounded up). */
export const IMPRESSION_CREDITS = Math.ceil(
  IMAGE_GENERATION_PRICE_USD / CREDIT_AI_USD,
);

/** Minimum top-up amount in credits (floor set by Stripe transaction costs). */
export const MIN_TOPUP_CREDITS = 75;

/** Per-action credit prices shown on the choose-action step. */
export const ACTION_CREDITS = {
  remove: 5,
  colorChange: 10,
  freePrompt: 10,
} as const;

/** The actions a user can pick on the choose-action step. */
export type RenovationAction = keyof typeof ACTION_CREDITS;
