/**
 * Client-side mirror of pricing constants from `functions/src/credits.ts`.
 * Keep these in sync with the server when tariffs change.
 */

/** Price per 1 M Gemini 2.5 Pro input tokens (USD). */
export const GEMINI_PRO_INPUT_PRICE_PER_M = 1.25;

/** Price per image generated by Gemini 2.5 Flash Image (USD). */
export const IMAGE_GENERATION_PRICE_USD = 0.039;

/** 1 user-facing credit, in USD. */
export const CREDIT_VALUE_USD = 0.01;

/** Fraction of credit value available for AI spending (80% after 20% platform fee). */
export const AI_BUDGET_RATIO = 0.8;

/** USD of AI budget unlocked per credit. */
export const CREDIT_AI_USD = CREDIT_VALUE_USD * AI_BUDGET_RATIO; // 0.008

/** Convert credits to USD price for the user. */
export function creditsToUsd(credits: number): number {
  return credits * CREDIT_VALUE_USD;
}

/** Credits required for a single image generation (rounded up). */
export const IMPRESSION_CREDITS = Math.ceil(
  IMAGE_GENERATION_PRICE_USD / CREDIT_AI_USD,
);
